apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.orderManagement.name }}-serviceaccount
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}
    component: orderManagement
