apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-@project.artifactId@
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}

data:
  db.schema: {{ .Values.@componentID@.db.schema }}
