{{- $ingress := .Values.ingress -}}
{{- if $ingress.enabled -}}
{{- $apiVersion := "networking.k8s.io/v1" -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $ingress.name }}
  namespace: {{ $ingress.namespace }}
  {{- with $ingress.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
          {{- range $ingress.paths }}
          - path: {{ tpl .path $ | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePortNumber }}
          {{- end }}
{{- end -}}
