config:
  remove_duplicates: true
  check_mandatory: true

# StringType, BinaryType, BooleanType, DecimalType, FloatType, DoubleType, ByteType, ShortType, IntegerType, LongType, DateType, TimestampType, NullType
fields:
  - name: adserver_id
    type: StringType()
    mandatory: true
  - name: id
    type: StringType()
    mandatory: true
  - name: name
    type: StringType()
    mandatory: true
  - name: adserver_target_type
    type: StringType()
    mandatory: true
  - name: status
    type: StringType()
    mandatory: true
  - name: dataProvider
    type: StringType()
    mandatory: true
  - name: type
    type: StringType()
    mandatory: true

# column order from list above
outputOrder:
  - adserver_id
  - id
  - name
  - adserver_target_type
  - status
  - dataProvider
  - type
