plan:
	terraform plan -var-file="../globals.tfvars" -compact-warnings

apply:
	terraform apply -auto-approve -var-file="../globals.tfvars" -compact-warnings

destroy: 
	terraform destroy -auto-approve -var-file="../globals.tfvars" -compact-warnings