params:

  - name: PARAMS.AWS_ACCOUNT_NUM
    value: 667518499308
    descirption: AWS account id where applications will be deployed

  - name: PARAMS.AWS_REGION
    value: ap-southeast-2
    descirption: AWS region where applications will be deployed

  - name: PARAMS.EKS_CLUSTER_NAME
    value: foxtel-hawkeye-prod-eks
    descirption: Cluster Name where applications will be deployed

  - name: PARAMS.VPC_CDIR_BLOCK
    value: 10.109.224.0/19
    descirption: VPC CDIR
  
  - name: PARAMS.ENV
    value: prod
    descirption: Types of environments eg dev, sit, uat, prod, to be used for the tag

  - name: PARAMS.CERT_ARN
    value: arn:aws:acm:ap-southeast-2:667518499308:certificate/192f9e3c-b029-4865-874b-df0fe3ae7c8b
    descirption: Arn of certifiacate to be applied to load balancer

  - name: PARAMS.TAGS
    value: Name=nlb-internal-prod-01
    descirption: Tags to add to the internal NLB
  
  - name: PARAMS.SUBNETS
    value: subnet-04345c7bcff4dd30b,subnet-0d6d5279251ba2972,subnet-0febacea2d58aa58b
    descirption: Private subnets to apply the nlb to


  - name: PARAMS.PUBLIC_SUBNETS
    value: subnet-0a4dd0c58ca3165eb,subnet-035a565ad387f1617,subnet-0b314c0b20ae98054
    descirption: Public subnets to apply the lb to
