apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-order-management
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}

data:
  db.schema: {{ .Values.orderManagement.db.schema }}
