apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ms-cookie
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}

data:
  server.servlet.session.cookie.name: "JSESSIONID"
