apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-settings-local
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}

data:
  spring.profiles.include: "no-jms,no-notification"
  spring.jpa.properties.hibernate.show_sql: "true"
  spring.jpa.properties.hibernate.use_sql_comments: "true"
  spring.jpa.properties.hibernate.format_sql: "true"
  logging.level.ROOT: "ALL"
  logging.level.com.acn: "ALL"
  management.endpoint.shutdown.enabled: "true"
  endpoints.shutdown.enabled: "true"
