{{- if .Values.@componentID@.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: {{ .Values.@componentID@.id }}
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}
    component: @componentID@
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^(/dashboard)$ $1/ redirect;
    nginx.ingress.kubernetes.io/rewrite-target: /$2

spec:
  rules:
    - host: {{.Values.@componentID@.ingress.host }}
      http:
        paths:
          - path: {{.Values.@componentID@.ingress.path }}(/|$)(.*)
            backend:
              serviceName: {{ .Values.@componentID@.name }}
              servicePort: {{ .Values.@componentID@.service.port }}

{{- end }}