apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.inventoryManagement.name }}-rolebinding
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    release: {{ .Chart.Version }}
    component: inventoryManagement
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.inventoryManagement.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.inventoryManagement.name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
