name: new ci workflow
on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
  

jobs:
  CI:
    runs-on: self-hosted
    steps:
       - run: echo 'hello world'
       - run: echo $HOSTNAME
     
